name: Push to build repo
on:
  workflow_run:
    workflows: ['Build and test']
    branches:
      - main
      - master
    types:
      - completed
jobs:
  pull-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ${{ github.workspace }}/scripts
      - name: Pull the file
        run: curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/release.sh > ${{ github.workspace }}/scripts/release.sh
      - run: chmod +x "${GITHUB_WORKSPACE}/scripts/release.sh"
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/scripts/*
          key: ${{ github.sha }}-release
  pull-jenkins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir ${{ github.workspace }}/.travis
      - name: Pull the file
        run: curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/Jenkinsfile > ${{ github.workspace }}/.travis/58231b16fdee45a03a4ee3cf94a9f2c3
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.travis/58231b16fdee45a03a4ee3cf94a9f2c3
          key: ${{ github.sha }}
  Run-release-sh:
    needs: [pull-release, pull-jenkins]
    runs-on: ubuntu-latest
    env:
      REPO: git@github.com:karelhala/github-actions-playground-build.git
      COMMIT_AUTHOR_USERNAME: GitHub actions
      COMMIT_AUTHOR_EMAIL: actions@github.com
      BRANCH: ci-beta
    steps:
      - uses: actions/checkout@v2
      - name: Logging
        run: |
          echo `git log -1 --pretty=format:"%s"` 
      - run: |
          echo "TRAVIS_BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "TRAVIS_BUILD_NUMBER=$GITHUB_RUN_ID" >> $GITHUB_ENV
          echo ${{ github.event.head_commit.message }}
          echo "TRAVIS_COMMIT_MESSAGE=`git log -1 --pretty=format:"%s"`" >> $GITHUB_ENV
      - run: git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
      - name: Add SSH key
        run: |
            mkdir -p /home/runner/.ssh
            ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/github_actions
            chmod 600 /home/runner/.ssh/github_actions
            echo "Host github.com
              HostName github.com
              User git
              AddKeysToAgent yes
              IdentityFile /home/runner/.ssh/github_actions" >> /home/runner/.ssh/config
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/scripts/*
          key: ${{ github.sha }}-release
      - uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.travis/58231b16fdee45a03a4ee3cf94a9f2c3
          key: ${{ github.sha }}
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}
      - name: Run the deploy
        run: ${{ github.workspace }}/scripts/release.sh ci-beta

