name: Push to build repo
on:
  workflow_run:
    workflows: ['Build and test']
    types:
      - completed
jobs:
  pull-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull the file
        run: curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/release.sh > ./scripts/release.sh
      - run: chmod +x "${GITHUB_WORKSPACE}/scripts/quay_push.sh"
      - uses: actions/cache@v2
        id: restore-scripts
        with:
          path: ${{ github.workspace }}/scripts/release.sh
          key: ${{ github.sha }}
  pull-jenkins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull the file
        run: curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/Jenkinsfile > ./.travis/58231b16fdee45a03a4ee3cf94a9f2c3
      - uses: actions/cache@v2
        id: restore-scripts
        with:
          path: ${{ github.workspace }}/.travis/58231b16fdee45a03a4ee3cf94a9f2c3
          key: ${{ github.sha }}
  Pull-release-sh:
    needs: [pull-release, pull-jenkins]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        id: restore-scripts
        with:
          path: ${{ github.workspace }}/scripts/release.sh
          key: ${{ github.sha }}-release
      - uses: actions/cache@v2
        id: restore-scripts
        with:
          path: ${{ github.workspace }}/.travis/58231b16fdee45a03a4ee3cf94a9f2c3
          key: ${{ github.sha }}
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ${{ github.workspace }}/dist/*
          key: ${{ github.sha }}
      - name: List files in the repository
        run: |
          ls -lah ${{ github.workspace }}
